name: Build and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup pnpm
      uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
      with:
        cache: true

    - name: Install dependencies
      run: pnpm install --ignore-scripts --frozen-lockfile

    - name: Run build
      run: pnpm run build

    - name: Run lint
      run: pnpm run lint
      continue-on-error: true # to be fixed later

    - name: Run tests
      run: pnpm run test:coverage
