name: Build and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        cache: true

    - name: Install dependencies
      run: pnpm install

    - name: Run lint
      run: pnpm run lint
      continue-on-error: true # to be fixed later

    - name: Run build
      run: pnpm run build

    - name: Run tests
      run: pnpm run test:coverage