name: Workflow Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions: {}

jobs:
  lint-workflows:
    name: Lint workflows
    runs-on: ubuntu-26.04
    permissions:
      checks: write  # Required by reviewdog actions to report check annotations.
      security-events: write  # Required for upload-sarif to send SARIF files.
      contents: read  # Only needed for private repos. Needed to clone the repo.
      actions: read  # Only needed for private repos to read workflow run info.
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: 🧾 Yamllint
        uses: reviewdog/action-yamllint@5dd4640db975e4cac6f4e775a401695bafc28068  # v1.25.1

      - name: 🛠️ Actionlint
        uses: reviewdog/action-actionlint@a8ac3eea598697a830f7d8e701fc9fcbfde88974  # v1.80.0

      - name: 🛡️ Zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482  # v0.6.4
        with:
          persona: pedantic
